Check if the HTTP server is up before running QUnit tests

diff --git a/bin/qunit b/bin/qunit
--- a/bin/qunit
+++ b/bin/qunit
@@ -8,9 +8,23 @@ while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symli
 done
 DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
 
-php -S 0.0.0.0:8080 &>/dev/null &
+function http_failed {
+  echo "Failed to start the HTTP server, abort."
+  kill ${SERVER_PID}
+  exit 1
+}
+
+php -S 127.0.0.1:8080 &>/dev/null &
 SERVER_PID=$!
+
+TRIES=10
+echo "HTTP server starting on 127.0.0.1:8080..."
+while ! nc -z 127.0.0.1 8080 &>/dev/null; do
+  sleep 0.1
+  ((--TRIES)) || http_failed
+done
+
 phantomjs ${DIR}/../tests/client/phantomjs-runner.js http://127.0.0.1:8080/tests.html
 EXIT_CODE=$?
-kill ${SERVER_PID}
+kill ${SERVER_PID} && echo "HTTP server stopped."
 exit ${EXIT_CODE}
